### ISSUE TITLE
fixer API not working without key

### ISSUE THREAD

**Issue by oaeide** [derkomai/Tickly#1]
It seemes fixer.io has changed from an open API endpoint to requiring a key. Maybe there is another provider that can be used?

Perhaps priceMulti from https://www.cryptocompare.com/api/#-api-data-price-

**Comment by dvilelaf** [comment]
Yes, I saw they started requiring an API. May be using your proposed API is the way to go. I'll try to take a look into it when I have some time (maybe next week).

**Comment by dvilelaf** [comment]
This issue should be fixed now with the new fiat rates api.
